services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Registrar todas as entidades da biblioteca
    ECidade\DataBaseLibrary\Entity\:
        resource: '../src/Entity'
        public: true

    # Registrar todos os repositórios da biblioteca
    ECidade\DataBaseLibrary\Repository\:
        resource: '../src/Repository'
        public: true
