version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: portal-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portalcidade
      MYSQL_USER: ecidade
      MYSQL_PASSWORD: ecidade
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  wordpress:
    image: wordpress:latest
    container_name: portal-wp
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ecidade
      WORDPRESS_DB_PASSWORD: ecidade
      WORDPRESS_DB_NAME: portalcidade
    ports:
      - "8080:80"
    volumes:
      - wordpress_data:/var/www/html

volumes:
  db_data:
  wordpress_data:
