security:

    providers:
        app_user_provider:
            entity:
                class: App\Entity\DbUsuario
                property: login

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~

    access_control:
        - { path: ^/api/configuracoes, roles: IS_AUTHENTICATED_FULLY }
