security:

    providers:
        jwt_user_provider:
            id: App\Security\JwtUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            provider: jwt_user_provider
            jwt: ~

    access_control:
        - { path: ^/api/configuracoes, roles: IS_AUTHENTICATED_FULLY }
